# Site settings
title: TylerHalfpop.com
email: me[at]tylerhalfpop[dot]com
description: > # 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tylerhalfpop.com"
twitter_username: tylerhalfpop
github_username:  tylerhalfpop
linkedin_username: tylerhalfpop

# Build settings
markdown: kramdown